spring.cloud.stream:
  function:
    definition: numberService
  bindings:
    numberService-in-0:
      destination: odd-even-numbers
  kafka:
    bindings:
      numberService-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.StringDeserializer
    binder:
      brokers:
        - localhost:9092
